defaults: &defaults
  instagram_client_id: "c9735368102d425a863fbdab9a88d195"
  instagram_client_secret: "7f57ff9f03504866b2718b7be0cc1829"
  instagram_access_token: "1930146428.c973536.611e4fecdde047c084647e3d6288a127"
  default_image_search_tag: "virtual"
  # If populated, the next three fields will appear at the end of page titles as "application_name - division_name - organization_name"
  application_name: "Your base app page title"
  division_name: "DHSI"
  division_url: "http://example.com/division_url"
  organization_name: "University name"
  meta_description: "A short description to include in the meta description tag"
  base_image_file_dir: "/path/to/directory/where/images/will/be/harvested"
  donor_agreement_text: "The text for your donor agreement that will be submitted as a comment"
  contact_email: "my_project@example.com"
  feed_description: "Description of this feed"
  # Uncomment to enable Google Analytics tracking
  # google_analytics_tracker: "UA-XXXXXXXX-XX"

development:
  <<: *defaults
  # Add or override config options here

test:
  <<: *defaults
  # Add or override config options here

staging:
  <<: *defaults
  # Add or override config options here

production:
  <<: *defaults
  # Add or override config options here
